name: tiiun
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.5
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.2.5
  firebase_remote_config: ^5.4.3
  firebase_app_check: ^0.3.0+2

  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0-beta.2
  connectivity_plus: ^6.1.4

  # State management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.10

  # Voice and audio
  just_audio: ^0.9.36
  record: ^5.0.4
  audio_session: ^0.1.18

  # Speech recognition and synthesis
  flutter_tts: ^3.8.5

  # UI packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter_markdown: ^0.6.18
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # API communication
  http: ^1.2.0
  dio: ^5.4.0

  # Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2

  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.2 # <-- 이 부분을 6.0.0에서 7.0.0으로 변경
  file_picker: ^10.1.9
  share_plus: ^7.2.1

  # AI and natural language processing
  langchain: ^0.0.7
  langchain_openai: ^0.0.5+1
  langchain_google: ^0.0.10+1

  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/contents/
    - assets/images/logos/
    - assets/images/mypage/
    - assets/images/diary/
    - assets/images/display/
    - assets/images/history/
    - assets/images/shop/
    - assets/images/dialog/


    - assets/icons/functions/
    - assets/icons/navbar/
    - assets/icons/sentiment/
    - assets/icons/buddy/
    - assets/icons/community/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100